<?php
/**
 * TaskCreateResult
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * VIN-API
 *
 * # Условия использования  Данные, получаемые в API не подлежат передаче третьим лицам. Предоставляются исключительно для личного пользования. В случае обнаружения нарушений, администрация в праве в одностороннем порядке заблокировать доступ к API до выяснения обстоятельств.  # Принцип работы API  API асинхронное. Для того чтобы получить данные по VIN сначала необходимо добавить задачу в очередь и получить ее уникальный идентификатор. После чего уже по этому идентификатору можно получить данные.  При постановке задачи в очередь, вы можете указать URL, на который по ее готовности система автоматически отправит POST запрос с результатом. Таким образом не нужно будет самим забирать результат. В случае, если URL окажется недоступен, система попробует повторить отправку от 1 до 5 раз с разными интервалами. В случае, если эти попытки окажутся безуспешными, система перестанет отправлять результат и необходимо будет уже самостоятельно сделать запрос в API на получение результата по идентификатору задачи. Успешным является запрос, в ходе которого удаленный сервер вернул статус 200. Все остальные статусы система рассматривает как безуспешные.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@autobius.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * TaskCreateResult Class Doc Comment
 *
 * @category    Class */
 // @description TaskCreateResult результат создания задачи
/** 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TaskCreateResult implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'TaskCreateResult';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'approximation' => 'bool',
        'date' => 'int',
        'decoder' => 'bool',
        'in_sale' => 'bool',
        'law' => 'bool',
        'success' => 'bool',
        'task_id' => 'string',
        'vin' => 'string'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'approximation' => 'approximation',
        'date' => 'date',
        'decoder' => 'decoder',
        'in_sale' => 'in_sale',
        'law' => 'law',
        'success' => 'success',
        'task_id' => 'task_id',
        'vin' => 'vin'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'approximation' => 'setApproximation',
        'date' => 'setDate',
        'decoder' => 'setDecoder',
        'in_sale' => 'setInSale',
        'law' => 'setLaw',
        'success' => 'setSuccess',
        'task_id' => 'setTaskId',
        'vin' => 'setVin'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'approximation' => 'getApproximation',
        'date' => 'getDate',
        'decoder' => 'getDecoder',
        'in_sale' => 'getInSale',
        'law' => 'getLaw',
        'success' => 'getSuccess',
        'task_id' => 'getTaskId',
        'vin' => 'getVin'
    );

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['approximation'] = isset($data['approximation']) ? $data['approximation'] : null;
        $this->container['date'] = isset($data['date']) ? $data['date'] : null;
        $this->container['decoder'] = isset($data['decoder']) ? $data['decoder'] : null;
        $this->container['in_sale'] = isset($data['in_sale']) ? $data['in_sale'] : null;
        $this->container['law'] = isset($data['law']) ? $data['law'] : null;
        $this->container['success'] = isset($data['success']) ? $data['success'] : null;
        $this->container['task_id'] = isset($data['task_id']) ? $data['task_id'] : null;
        $this->container['vin'] = isset($data['vin']) ? $data['vin'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        return true;
    }


    /**
     * Gets approximation
     * @return bool
     */
    public function getApproximation()
    {
        return $this->container['approximation'];
    }

    /**
     * Sets approximation
     * @param bool $approximation Будет ли доступна аппроксимация в результате
     * @return $this
     */
    public function setApproximation($approximation)
    {
        $this->container['approximation'] = $approximation;

        return $this;
    }

    /**
     * Gets date
     * @return int
     */
    public function getDate()
    {
        return $this->container['date'];
    }

    /**
     * Sets date
     * @param int $date Дата регистрации задачи в системе в формате UnixTimestamp
     * @return $this
     */
    public function setDate($date)
    {
        $this->container['date'] = $date;

        return $this;
    }

    /**
     * Gets decoder
     * @return bool
     */
    public function getDecoder()
    {
        return $this->container['decoder'];
    }

    /**
     * Sets decoder
     * @param bool $decoder Будет ли доступен результат VIN декодера
     * @return $this
     */
    public function setDecoder($decoder)
    {
        $this->container['decoder'] = $decoder;

        return $this;
    }

    /**
     * Gets in_sale
     * @return bool
     */
    public function getInSale()
    {
        return $this->container['in_sale'];
    }

    /**
     * Sets in_sale
     * @param bool $in_sale Будут ли доступны данные об автомобилях в продаже в резкльтате
     * @return $this
     */
    public function setInSale($in_sale)
    {
        $this->container['in_sale'] = $in_sale;

        return $this;
    }

    /**
     * Gets law
     * @return bool
     */
    public function getLaw()
    {
        return $this->container['law'];
    }

    /**
     * Sets law
     * @param bool $law Будут ли доступны в результате юридические данные
     * @return $this
     */
    public function setLaw($law)
    {
        $this->container['law'] = $law;

        return $this;
    }

    /**
     * Gets success
     * @return bool
     */
    public function getSuccess()
    {
        return $this->container['success'];
    }

    /**
     * Sets success
     * @param bool $success
     * @return $this
     */
    public function setSuccess($success)
    {
        $this->container['success'] = $success;

        return $this;
    }

    /**
     * Gets task_id
     * @return string
     */
    public function getTaskId()
    {
        return $this->container['task_id'];
    }

    /**
     * Sets task_id
     * @param string $task_id Уникальный идентификатор задачи
     * @return $this
     */
    public function setTaskId($task_id)
    {
        $this->container['task_id'] = $task_id;

        return $this;
    }

    /**
     * Gets vin
     * @return string
     */
    public function getVin()
    {
        return $this->container['vin'];
    }

    /**
     * Sets vin
     * @param string $vin
     * @return $this
     */
    public function setVin($vin)
    {
        $this->container['vin'] = $vin;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


