<?php
/**
 * DecoderResultTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * VIN-API
 *
 * # Условия использования  Данные, получаемые в API не подлежат передаче третьим лицам. Предоставляются исключительно для личного пользования. В случае обнаружения нарушений, администрация в праве в одностороннем порядке заблокировать доступ к API до выяснения обстоятельств.  # Принцип работы API  API асинхронное. Для того чтобы получить данные по VIN сначала необходимо добавить задачу в очередь и получить ее уникальный идентификатор. После чего уже по этому идентификатору можно получить данные.  При постановке задачи в очередь, вы можете указать URL, на который по ее готовности система автоматически отправит POST запрос с результатом. Таким образом не нужно будет самим забирать результат. В случае, если URL окажется недоступен, система попробует повторить отправку от 1 до 5 раз с разными интервалами. В случае, если эти попытки окажутся безуспешными, система перестанет отправлять результат и необходимо будет уже самостоятельно сделать запрос в API на получение результата по идентификатору задачи. Успешным является запрос, в ходе которого удаленный сервер вернул статус 200. Все остальные статусы система рассматривает как безуспешные.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@autobius.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DecoderResultTest Class Doc Comment
 *
 * @category    Class */
// * @description DecoderResult результат собранный по данным VIN декодера
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DecoderResultTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "DecoderResult"
     */
    public function testDecoderResult()
    {

    }

    /**
     * Test attribute "assembly_plant"
     */
    public function testPropertyAssemblyPlant()
    {

    }

    /**
     * Test attribute "body"
     */
    public function testPropertyBody()
    {

    }

    /**
     * Test attribute "brand"
     */
    public function testPropertyBrand()
    {

    }

    /**
     * Test attribute "brand_owner"
     */
    public function testPropertyBrandOwner()
    {

    }

    /**
     * Test attribute "complete"
     */
    public function testPropertyComplete()
    {

    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {

    }

    /**
     * Test attribute "country_code"
     */
    public function testPropertyCountryCode()
    {

    }

    /**
     * Test attribute "doors"
     */
    public function testPropertyDoors()
    {

    }

    /**
     * Test attribute "drive"
     */
    public function testPropertyDrive()
    {

    }

    /**
     * Test attribute "engine"
     */
    public function testPropertyEngine()
    {

    }

    /**
     * Test attribute "engine_size"
     */
    public function testPropertyEngineSize()
    {

    }

    /**
     * Test attribute "engine_volume"
     */
    public function testPropertyEngineVolume()
    {

    }

    /**
     * Test attribute "equipment"
     */
    public function testPropertyEquipment()
    {

    }

    /**
     * Test attribute "equipment_option_codes"
     */
    public function testPropertyEquipmentOptionCodes()
    {

    }

    /**
     * Test attribute "equipment_options"
     */
    public function testPropertyEquipmentOptions()
    {

    }

    /**
     * Test attribute "generation"
     */
    public function testPropertyGeneration()
    {

    }

    /**
     * Test attribute "horsepower"
     */
    public function testPropertyHorsepower()
    {

    }

    /**
     * Test attribute "is_primary"
     */
    public function testPropertyIsPrimary()
    {

    }

    /**
     * Test attribute "manufacturer"
     */
    public function testPropertyManufacturer()
    {

    }

    /**
     * Test attribute "manufacturer_id"
     */
    public function testPropertyManufacturerId()
    {

    }

    /**
     * Test attribute "mark"
     */
    public function testPropertyMark()
    {

    }

    /**
     * Test attribute "market"
     */
    public function testPropertyMarket()
    {

    }

    /**
     * Test attribute "market_info"
     */
    public function testPropertyMarketInfo()
    {

    }

    /**
     * Test attribute "model"
     */
    public function testPropertyModel()
    {

    }

    /**
     * Test attribute "model_year_end"
     */
    public function testPropertyModelYearEnd()
    {

    }

    /**
     * Test attribute "model_year_start"
     */
    public function testPropertyModelYearStart()
    {

    }

    /**
     * Test attribute "modification"
     */
    public function testPropertyModification()
    {

    }

    /**
     * Test attribute "recall_source"
     */
    public function testPropertyRecallSource()
    {

    }

    /**
     * Test attribute "technical_info"
     */
    public function testPropertyTechnicalInfo()
    {

    }

    /**
     * Test attribute "transmission"
     */
    public function testPropertyTransmission()
    {

    }

    /**
     * Test attribute "vds"
     */
    public function testPropertyVds()
    {

    }

    /**
     * Test attribute "vehicle_type"
     */
    public function testPropertyVehicleType()
    {

    }

    /**
     * Test attribute "vin"
     */
    public function testPropertyVin()
    {

    }

    /**
     * Test attribute "vin_validation"
     */
    public function testPropertyVinValidation()
    {

    }

    /**
     * Test attribute "vis"
     */
    public function testPropertyVis()
    {

    }

    /**
     * Test attribute "warnings"
     */
    public function testPropertyWarnings()
    {

    }

    /**
     * Test attribute "was_recalled"
     */
    public function testPropertyWasRecalled()
    {

    }

    /**
     * Test attribute "wheel"
     */
    public function testPropertyWheel()
    {

    }

    /**
     * Test attribute "wmi"
     */
    public function testPropertyWmi()
    {

    }

    /**
     * Test attribute "year"
     */
    public function testPropertyYear()
    {

    }

}
